---
- hosts: controller
  remote_user: vagrant
  sudo: True
  roles:
      - common
      - database
      - mq
      - keystone
      - nova-controller
      - neutron-controller
      - dashboard
      - cinder-controller
      - glance
